name: Check website for broken links

on:
  # Trigger the workflow every time you push to the `main` branch
  push:
    branches: [ main ]
  # Run link check on any pull request.
  pull_request:
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and perform a link check
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./website
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install pnpm as package manager
        uses: pnpm/action-setup@v6
        with:
          version: 11
          # cache: true
          run_install: true
            #- cwd: website

      - name: Build website
        run: pnpm build

      - name: Check links using hyperlink
        uses: untitaker/hyperlink@1ae2cef25222e3307a82bc7388f0667137f4240b # 0.2.1
        with:
          args: --check-anchors website/dist
